name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check flake
    runs-on: macos-15
    timeout-minutes: 5

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Check formatting
        run: nix fmt -- --ci

      - name: Build command-line tools
        run: nix build --no-link -L .#checks.aarch64-darwin.command-line-tools

      - name: Test Darwin module
        run: nix build --no-link -L .#checks.aarch64-darwin.darwin-module

      - name: Test Home Manager module
        run: nix build --no-link -L .#checks.aarch64-darwin.home-module
